<!-- dom:TITLE: TD 12 : Tableaux et calcul matriciel avec NumPy -->
# TD 12 : Tableaux et calcul matriciel avec NumPy
<!-- dom:AUTHOR: Ahmed Ammar Email:ahmed.ammar@fst.utm.tn at Classes Sup : IPEST-La Marsa, Universit\'e de Carthage. -->
<!-- Author: -->  
**Ahmed Ammar** (email: `ahmed.ammar@fst.utm.tn`), Classes Sup : IPEST-La Marsa, Universit\'e de Carthage.

Date: **Lundi, 17 mai 2021**

<!-- TOC: on -->

Pour manipuler les matrices, nous importerons le module numpy par `import numpy as np`. Ce module permet de coder plus efficacement les matrices (ligne, colonne ou rectangulaire) que la structure classique de liste par les contraintes plus fortes qui existent sur le type `array` :
* un tableau est homogène (il ne contient que des entiers, ou que des flottants, ou que des booléens...) ;

* un tableau n'est pas redimensionnable (contrairement à une liste, à laquelle on peut ajouter un élément avec append).

Comme conséquence du premier point : si, lors de le création d’un tableau, on mélange des flottants et des entiers, il y a conversion automatique des entiers en flottants par exemple.
### Copie

Comme pour les listes, la définition $t_1 = t$ ne crée pas une copie du tableau $t$, mais un deuxième nom pour le même tableau. Ainsi, toute modification effectuée sur $t_1$ est aussi effectuée sur t : c’est le même tableau! Pour créer une copie du tableau, il faut écrire `t1 = np.copy(t)`.

### Slicing et vues

Si $l$ est une liste, un peut en obtenir une tranche par la syntaxe `l[1:4]` : c’est la sous-liste formée des éléments de $l$ dont les indices appartiennent à l’ensemble $[1, 4[$. Cette tranche est une copie de la liste : si l’on définit une nouvelle liste par `l1 = l[1:4]`, une modification de la liste `l1` n’entraîne aucune modification de la liste l (et inversement).

Pour les tableaux en revanche, la même syntaxe renvoie une vue sur le tableau : si l’on définit `t1` par
`t1 = t[1:4]`, `t1` désigne une partie du tableau `t`. Par suite, toute modification effectuée sur `t1` se répercute sur `t` (et inversement).

In [1]:
import numpy as np

## Exercise 1: Calcul matriciel

Soit les matrices suivantes :
$$ R =\left( \begin{array}{ccc} 1 &2 &3 \\ 4 &5 &6 \end{array} \right) \ , \ S = \left( \begin{array}{ccc} 1 &-1 &3 \\ 2 &-1 &0 \\ -1 &0 &-2 \end{array} \right) \ et \ T = \left( \begin{array}{ccc} 1 &1 &-2 \\ 1 &0 &-1 \\ 1 &0 &-1 \end{array} \right)$$

### Trace d'une matrice

Pour une matrice carrée, on appelle trace la somme des coefficients de la diagonale de la matrice.
* **Q1.** Écrire une fonction `trace(M)` qui prend en entrée une matrice carrée $M$ et renvoie la trace de la matrice.

In [2]:
R= np.array([[1, 2, 3], [4, 5, 6]])
S= np.array([[1, -1,3], [2,-1,0],[-1,0,-2]])
T= np.array([[1,1,-2],[1,0,-1],[1,0,-1]])

In [3]:
# Q1.
def trace(M):
    trace=0
    n=len(M)
    for k in range(n):
        trace+=M[k,k]
    return trace

* **Q2.** Tester votre fonction avec la matrice $S$.

In [4]:
# Q2.
trace(S)

-2

In [5]:
# avec numpy
np.trace(S)

-2

* **Q3.** Ajouter un test dans votre fonction qui permettra de renvoyer le texte `"La matrice n’est pas carrée ! "` si la matrice $M$ entrée n’est pas carrée.

In [6]:
# Q3.
def trace(M):
    trace=0
    n=len(M)
    if M.shape[0] != M.shape[1]:
        return "La matrice n'est pas carrée! "
    else:
        for k in range(n):
            trace+=M[k,k]
        return trace

* **Q4.** Tester votre fonction avec la matrice $R$.

In [7]:
# Q4.
trace(R)

"La matrice n'est pas carrée! "

### Transposée d'une matrice

* **Q1.** Écrire une fonction `transpose(M)` qui prend en entrée une matrice M et renvoie la transposée de cette matrice.

In [8]:
# Q1.
def transpose(M):
    n, p =M.shape[0], M.shape[1]
    Transp=np.zeros((p,n))
    for i in range(n):
        for j in range(p):
            Transp[j,i]=M[i,j]
    return Transp

* **Q2.** Tester votre fonction avec la matrice R.

In [9]:
# Q2.
print("R = \n", R)
print("R_T = \n", transpose(R))

R = 
 [[1 2 3]
 [4 5 6]]
R_T = 
 [[1. 4.]
 [2. 5.]
 [3. 6.]]


### Produit matriciel

* **Q1.** Écrire une fonction produit(A,B) qui prend en entrée deux matrices et renvoie le produit des deux matrices. (en supposant que celui-ci est possible).

In [10]:
# Q1.
def produit(A,B):
    n, p, q = A.shape[0], A.shape[1], B.shape[1]
    C = np.zeros((n,q))
    for i in range(n):
        for j in range(q):
            for k in range(p):
                C[i,j] += A[i,k]*B[k,j]
    return C

* **Q2.** Tester votre fonction avec les matrices R et S. *Faire le produit dans le bon sens !*

In [11]:
# Q2.
produit(R, S)

array([[ 2., -3., -3.],
       [ 8., -9.,  0.]])

In [12]:
# avec numpy
R @ S #np.dot(R, S)

array([[ 2, -3, -3],
       [ 8, -9,  0]])

* **Q3.** En profiter pour calculer le cube de la matrice $T$. Que peut-on en déduire ?

In [13]:
# Q3.
T2 = produit(T, T)
produit(T2, T)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

<span style="color:blue">**Déduction :**</span>.

<span style="color:blue">Il existe un vecteur $x$ tel que $T^2 x \ne 0$; à partir de là on écrit *l'endomorphisme* représenté dans la base $\{x, T x, T^2 x \}$</span>.


* **Q4.** Ajouter un bloc `try:...except:...` dans votre fonction qui permettra de renvoyer le texte `"Le produit n’est pas possible ! "` si le produit matriciel est impossible à effectuer.

In [14]:
# Q4.
def produit(A,B):
    n, p, q = A.shape[0], A.shape[1], B.shape[1]
    C = np.zeros((n,q))
    try:
        for i in range(n):
            for j in range(q):
                for k in range(p):
                    C[i,j] += A[i,k]*B[k,j]
        return C
    except IndexError:
        return "Le produit n'est pas possible!"

* **Q5.** Tester votre fonction avec les matrices R et S. *Faire le produit dans le mauvais sens cette fois !*

In [15]:
# Q5.
produit(S, R)

"Le produit n'est pas possible!"

## Exercise 2: Systèmes linéaires
<div id="sec:sys_lin"></div>

* **Q1.** Écrire des fonctions `transvecLigne(A,i,j,c)`, `permutLigne(A,i,j)` et `dilatLigne(A,i,c)` telles que `transvecLigne(A,i,j,c)` modifie la matrice $A$ par l’opération $L_i \leftarrow L_i +  c L_j$ (et des opérations similaires pour les deux autres fonctions). Ces fonctions modifient la matrice passée en argument et ne renvoient rien.

In [2]:
# Q1.
def transvecLigne(A ,i ,j ,c):
    """opération L_i <-- L_i + c * L_j sur A."""
    A[i] += c * A[j]

def permutLigne(A, i1, i2):
    """ permute les lignes d'indices i1 et i2 de A."""
    A[i1], A[i2] = np.copy(A[i2]), np.copy(A[i1])
    
def dilatLigne(A ,i ,c):
    """opération L_i <-- c * L_i sur A."""
    A[i] *= c
def transvecCol (A, i, j, c):
    """ opération L_i <-- c * L_i sur A."""
    A[:, i] += c * A[:, j]

* **Q2. a)** Écrire une fonction `systLin(A,B)` qui résout le système linéaire de matrice $A$ (carrée et inversible) et de second membre $B$ par la méthode du *pivot de Gauss*. La fonction ne devra modifier ni la matrice $A$, ni la matrice $B$ (il faudra en faire des copies, sur lesquelles on fera les opérations). La matrice $B$ ne sera pas nécessairement une matrice colonne (quel format doit avoir l’inconnue $X$ lorsque $B$ a $p$ colonnes ?). Quel est le résultat renvoyé lorsque l’on prend $B = I_n$ ?

In [3]:
# Q2.a)
def systLin(A, B):
    n = len(A)
    A1 = np.copy(A)
    B1 = np.copy(B)
    for j in range(n-1):
        for i in range(j+1, n):
            # pivot
            c = A1[i, j]/A1[j, j]
            # annuler les coeffs Ai,j pour i>j
            transvecLigne(A1 ,i ,j ,-c)
            transvecLigne(B1 ,i ,j ,-c)
    
    # phase de remontée
    for j in range(n-1, -1, -1):
        for i in range(j-1 ,-1 ,-1):
            # pivot
            c = A1[i ,j]/A1[j, j]
            # annuler les coeffs au-dessus du diag principal
            transvecLigne(A1 ,i ,j , -c)
            transvecLigne(B1 ,i ,j , -c)
        # le système est diagonale --> dilatation pour obtenir les xi
        dilatLigne(B1 ,j ,1/A1[j,j])
    return B1

* <span style="color:blue">**Quel format doit avoir l’inconnue $X$ lorsque $B$ a $p$ colonnes ?**</span>

Si la matrice $B$ comporte $p$ colonnes, l’inconnue $X$ doit aussi en comporter $p$ ; la résolution du système $A [X_1 \dots X_p] = [B_1 \dots B_p]$ équivaut à la résolution des $p$ systèmes linéaires $AX_i = B_i$.


* <span style="color:blue">**Quel est le résultat renvoyé lorsque l’on prend $B = I_n$ ?**</span>


Lorsque l'on prend $B = I_n$, la solution calculée est la matrice $A^{-1}$.


* **b)** Évaluer le nombre de multiplications (ou divisions) effectuées pour la résolution du système (dans le cas où $B$ est une matrice colonne).

<span style="color:blue">**SOLUTION : b)**</span> 

Dans la **phase de descente** :
* pour chaque passage dans la boucle indexée par $i$, on effectue une division et $n + 1$ multiplications.
* pour chaque valeur de $i$ entre $j+1$ et $n-1$, il y a $(n - 1) - (j + 1) + 1 = n - j - 1$ passages dans cette boucle.

L’indice j varie de 0 à $n - 1$, donc il y a $$(n+2) \sum_{j = 0}^{n-1} \sum_{i = j+1}^{n-1} 1 = (n+2) \sum_{j = 0}^{n-1} (n - j - 1) \approx (n+2) \frac{n(n-1)}{2}$$

La **phase de remontée** comporte autant d’opérations, ainsi que quelques dilatations.

Au total, le nombre d’opérations est équivalent à $n^3$.


* **Q3.** Dans la pratique, on rencontre parfois un pivot nul sur la diagonale principale. Il faut alors permuter la ligne correspondante avec une ligne située en-dessous pour retrouver un pivot non nul et poursuivre l’algorithme. Cette opération de permutation est intéressante même lorsque le pivot diagonal n’est pas nul : utiliser le plus grand (en valeur absolue) pivot possible permet de réduire l’effet des erreurs d’arrondi résultant des divisions par le pivot.

* **a)** Tester la fonction `systLin(A,B)` sur le système linéaire :

$$\left\{ \begin{array}{*{5}{c}}
	10^{-20}x & + & y & = & 1 \\
	x & + & y & = & 2 \\
\end{array} \right.$$
et comparer à la véritable solution (calculée à la main).

In [4]:
# Q3 a)
A = np.array([[1e-20, 1], [1, 1]])
B = np.array([[1.], [2]])
systLin(A, B)

array([[0.],
       [1.]])


La solution exacte est donnée par :
$$x = \dfrac{
\begin{vmatrix}
1 &1 \\
2 &1
\end{vmatrix}
}{\begin{vmatrix} 
10^{-20} &1 \\
1 &1
\end{vmatrix}} = \dfrac{-1}{10^{-20} - 1}\approx 1 \quad et \quad y = \dfrac{
\begin{vmatrix}
10^{-20} &1 \\
1 &2
\end{vmatrix}
}{\begin{vmatrix} 
10^{-20} &1 \\
1 &1
\end{vmatrix}} = \dfrac{2\times10^{-20} - 1}{10^{-20} - 1}\approx 1$$



* **b)** Écrire une fonction `pivot(A,j)` qui renvoie l’indice $i$ du plus grand (en valeur absolue) des coefficients $A_{j,j} , . . . , A_{n-1,j}$ ($n$ : nombre le lignes de la matrice).

In [5]:
# Q3 b) 
def pivot(A, j):
    n = len(A)
    imax = j
    for i in range(j+1, n):
        if abs(A[i, j]) > abs(A[imax, j]):
            imax = i
    return imax

* **c)** Écrire une fonction `systLinPivot(A,B)`, spécifiée comme `systLin(A,B)`, mais qui utilise la méthode du pivot partiel.

In [6]:
# Q3 c)
def systLinPivot(A,B):
    n = len(A)
    A1 = np.copy(A)
    B1 = np.copy(B)
    for j in range(n-1):
        # plus grand pivot possible
        imax = pivot(A1, j)
        permutLigne(A1, j, imax)
        permutLigne(B1, j, imax)
        for i in range(j+1, n):
            # pivot
            c = A1[i, j]/A1[j, j]
            # annuler les coeffs Ai,j pour i>j
            transvecLigne(A1 ,i ,j ,-c)
            transvecLigne(B1 ,i ,j ,-c)
    # phase de remontée
    for j in range(n-1, -1, -1):
        for i in range(j-1 ,-1 ,-1):
            # pivot
            c = A1[i ,j]/A1[j, j]
            # annuler les coeffs au-dessus du diag principal
            transvecLigne(A1 ,i ,j , -c)
            transvecLigne(B1 ,i ,j , -c)
        # le système est diagonale --> dilatation pour obtenir les xi
        dilatLigne(B1 ,j ,1/A1[j,j])
    return B1

* Tester la fonction sur le système précédent.

In [7]:
systLinPivot(A, B)

array([[1.],
       [1.]])

* **Q4.** Écrire une fonction `determinant(A)` qui calcule le déterminant d’une matrice.

In [8]:
# Q4. 
def determinant(A):
    n = len(A)
    A1 = np.copy(A)
    signe = 1
    for j in range(n-1):
        imax = pivot(A1, j)
        if imax > j : # chaque échange d’une ligne avec une autre
            # change le signe du déterminant de la matrice
            signe = - signe
            permutLigne(A1, j, imax)
        for i in range(j+1, n):
            c = A1[i, j]/A1[j, j]
            transvecLigne(A1, i, j, -c)
    produit = signe
    for j in range(n):
        produit *= A1[j, j]
    return produit

In [9]:
determinant(A)

-1.0

### Décomposition LU

Lorsque l’on a de nombreux systèmes linéaires à résoudre avec la même matrice $A$ (inversible), il peut être judicieux de trouver une décomposition de $A$ sous la forme $A = LU$ , où $L$ est triangulaire inférieure (lower) et $U$ triangulaire supérieure (upper). En introduisant l’inconnue $Z$ définie par $Z = U Y$ , la résolution du système linéaire $AX = Y$ est alors ramenée à la résolution de deux systèmes plus simples (car triangulaires) : $LZ = Y$ et $U X = Z$.

L’algorithme pour trouver cette décomposition consiste à manipuler deux suites $(L_k)_k$ et $(U_k)_k$ de matrices vérifiant $L_k U_k = A$ pour tout $k$. On initialise avec $L_0 = I_n$ et $U_0 = A$. Puis on pratique l’algorithme du pivot de Gauss sur la matrice $U$ pour la transformer en matrice échelonnée en lignes (donc triangulaire supérieure). Pour cela, on lui fait subir des opérations du type $L_i \leftarrow L_i + \lambda L_j$ , avec $i > j$. Autrement dit, on passe de la matrice $U_k$ à la matrice $U_{k+1}$ par une opération du type $U_{k+1} = T_{i,j,\lambda} U_k$ (les valeurs de $i$, $j$ et $\lambda$ changeant bien sûr à chaque étape). 

Pour conserver l’égalité $L_{k+1} U_{k+1} = A$, il faut alors poser $L_{k+1} = L_k T_{i,j,\lambda}^{-1} = L_k T_{i,j,-\lambda}$ , i.e. passer de la matrice $L_k$ à $L_{k+1}$ par l’opération $C_j \leftarrow C_j - \lambda C_i$.

À la fin de l’algorithme, la matrice $U$ est triangulaire supérieure, et la matrice $L$ triangulaire inférieure, ses coefficients diagonaux étant tous égaux à 1. En effet, par construction, la matrice $L$ est un produit de matrices de transvections $T_{i,j,-\lambda}$ avec à chaque fois $i \ge j$. Ces matrices sont toutes triangulaires inférieures de coefficients diagonaux égaux à 1, donc il en est de même de leur produit.

* **Q5.** Traiter à la main l’exemple de la matrice
$$A = \left( \begin{array}{ccc} 1 &4 &-2 \\ 2 &6 &1 \\ 3 &5 &3 \end{array} \right)$$

* <span style="color:blue">**Q5. clacul à la main :**</span>

L'application de l'algorith à la main donne :
$$L = \left( \begin{array}{ccc} 1 &0 &0 \\ 2 &1 &0 \\ 3 &\dfrac{7}{2} &1 \end{array} \right) \quad et \quad U = \left( \begin{array}{ccc} 1 &4 &-2 \\ 0 &-2 &5 \\ 0 &0 &\dfrac{-17}{2} \end{array} \right)$$
-->

* **Q6.** Écrire une fonction `LU(A)` qui renvoie le couple `(L, U)` de la décomposition $A = LU$. Vérifier que l’on retrouve bien le résultat obtenu à la main sur l’exemple précédent.


In [13]:
# Q6.
def LU(A):
    n = len(A)
    L = np.identity(n) # np.eye(n)
    U = np.copy(A)
    for j in range(n-1):
        for i in range(j+1, n):
            c = U[i, j]/U[j, j]
            transvecLigne (U, i, j, -c)
            transvecCol(L, j, i, c)
    return (L, U)

In [11]:
A = np.array([[1, 4, -2], [2, 6, 1], [3, 5, 3]], dtype=np.float_)
L, U = LU(A)
print("L = \n", L)
print("U = \n", U)

L = 
 [[1.  0.  0. ]
 [2.  1.  0. ]
 [3.  3.5 1. ]]
U = 
 [[ 1.   4.  -2. ]
 [ 0.  -2.   5. ]
 [ 0.   0.  -8.5]]


In [12]:
np.dot(L, U)

array([[ 1.,  4., -2.],
       [ 2.,  6.,  1.],
       [ 3.,  5.,  3.]])